---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ledger-api-secret
  namespace: default
spec:
  encryptedData:
    API_KEY: AgBBE4Pz4AnWL7zfkF5gvynI//VVCTK4CVb7KkVIvbVaOTYuFSRocmFTlDKNRWngvo4sxsNqicF/hENTIlcSmmj2uQS0cofSqyvZsiIy2Oh1xmYYZz+S30YXwLBUPiBWWZBhJdr9wA/cM6ogqi2ZprvdAXPxzC0EKYyQqCRXeYLUJIda7C83wDcpXdi8+1Ss+tCKLLm5UQbSXmFwgw4bWOjQEZP43haY5sO1q2D6+24pzrvUBvuaev3hKWbAdHLPoy5OTFax34/C5+klSqhGoAJSW6psrJ/xg//xARVuEPw4XO1fSSbmdEps2jWxAas03/tnMdzyZZo+ZKBHFA25s+WBVnyN5tWcjxn88aRKweIHNeiQT/t3m09qlk7S9kFikm9wvqRM/rzy6+X1rmRhPx0TKKlZhPgChdcjMs1q8MwZ8FpJlM5KhmPQppXBVaSD8Zqw4ZlULuuXhG5/2UWuWNmKjk918N9vAdWX/+tt/M1kKy/rarXatlDGIeRUylqIH+TjGjUl1LygSTU84CqI5qtNkvrIdTnZgPlbGrT50a8PExbqCgiPkRAMD5yqIul1B3cSnFYxjAZuvDfW/UVRtlKwpo2rv8gMswzr38aOvZzyFbhKMBVsEKGv5uFkxbnqlgEL7B/29B8dCXf3/AEftBy+qjNH6vQsW4pOXCYK/M7gpQHwp3X9QyoFuG91Mb1/5e5rRRXuOxgrNl9XCJHyR4wjDuzE
  template:
    metadata:
      creationTimestamp: null
      name: ledger-api-secret
      namespace: default
    type: Opaque
